apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Monu-nashtech-devops/ArgoCd-project.git
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod     # 👈 Changed from 'default' to 'prod'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

