apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # ✅ GOOD: No "namespace" field here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: node-app
          image: node:16-alpine
          ports:
            - containerPort: 3000
