apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  # ✅ GOOD: No "namespace" field here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: react-app
          image: nginx:alpine
          ports:
            - containerPort: 80
